# Generated by Django 5.1.5 on 2025-04-23 14:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoundItem',
            fields=[
                ('item_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('date_found', models.DateField()),
                ('location', models.CharField(max_length=255)),
                ('posted_by_id', models.CharField(max_length=20)),
                ('posted_by_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='LostItem',
            fields=[
                ('item_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('date_lost', models.DateField()),
                ('location', models.CharField(max_length=255)),
                ('posted_by_id', models.CharField(max_length=20)),
                ('posted_by_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='LostItemImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='lost_items/')),
                ('lost_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='tracker.lostitem')),
            ],
        ),
    ]
