# Generated by Django 5.1.5 on 2025-05-02 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_comment_upvote'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='upvote',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='upvote',
            name='item',
        ),
        migrations.RemoveField(
            model_name='upvote',
            name='user',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Upvote',
        ),
    ]
