# Generated by Django 5.1.5 on 2025-05-06 13:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0005_alter_upvote_unique_together_remove_upvote_item_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('item_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('date_reported', models.DateField()),
                ('location', models.CharField(max_length=255)),
                ('posted_by_id', models.CharField(max_length=20)),
                ('posted_by_name', models.CharField(max_length=255)),
                ('is_found', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ItemImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='items/')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='tracker.item')),
            ],
        ),
        migrations.DeleteModel(
            name='FoundItem',
        ),
        migrations.RemoveField(
            model_name='lostitemimage',
            name='lost_item',
        ),
        migrations.DeleteModel(
            name='LostItem',
        ),
        migrations.DeleteModel(
            name='LostItemImage',
        ),
    ]
