# Generated by Django 5.1.5 on 2025-05-09 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0007_alter_itemimage_item_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='claim_image',
            field=models.ImageField(blank=True, null=True, upload_to='claims/'),
        ),
    ]
