# Generated by Django 5.1.5 on 2025-05-09 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0008_item_claim_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='claimer_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='claimer_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
